language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.1
# avoid having travis install jdk on MRI builds where we don't need it.
matrix:
  include:
    - jdk: oraclejdk8
      rvm: jruby-9.0.5.0
    - jdk: oraclejdk8
      rvm: jruby-9.1.15.0

