language: ruby
cache: bundler
sudo: false
rvm:
  - jruby-19mode
  - jruby-9.0.4.0
  - 1.9
  - 2.2
  - 2.3.0
  - rbx-2
before_install:
  - gem update --system
  - gem install bundler --version='~>1.7'
jdk:
  - oraclejdk8
