language: ruby
rvm:
  - jruby-19mode
  - jruby-head
  - 1.9.3
  - 2.1.1
  - rbx-2
jdk:
  - openjdk7
  - openjdk6
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 2.1.1
      jdk: openjdk7
    - rvm: rbx-2
      jdk: openjdk7
    - rvm: jruby-head
      jdk: openjdk6
  allow_failures:
    - rvm: jruby-head

bundler_args: --without debug
